### ISSUE TITLE
"Streaming Decode/Search Directly from S3 Remote Storage" Sample Code Not Working with Latest Version of `smart_open`

### ISSUE THREAD

**Issue by junhaoliao** [y-scope/clp-ffi-py#59]
### Bug

It was found that with latest version of `smart_open`, below sample code (derived from https://github.com/y-scope/clp-ffi-py#streaming-decodesearch-directly-from-s3-remote-storage ) raises an exception during decoding:

```py
from clp_ffi_py.ir import ClpIrStreamReader

import smart_open

url = 'https://yscope.s3.us-east-2.amazonaws.com/sample-logs/yarn-ubuntu-resourcemanager-ip-172-31-17-135.log.1.clp.zst'
# Using `smart_open.open` to stream the encoded CLP IR:
with smart_open.open(url, "rb") as istream:
    with ClpIrStreamReader(istream, allow_incomplete_stream=True) as clp_reader:
        for log_event in clp_reader:
            # Print the log message with its timestamp properly formatted.
            print(log_event.get_formatted_message())
```
Raises:
```
Traceback (most recent call last):
  File "/Users/jliao8/PycharmProjects/athena-script/main.py", line 19, in <module>
    with ClpIrStreamReader(istream, allow_incomplete_stream=True) as clp_reader:
  File "/Users/jliao8/PycharmProjects/athena-script/.venv/lib/python3.9/site-packages/clp_ffi_py/ir/readers.py", line 115, in __enter__
    self.read_preamble()
  File "/Users/jliao8/PycharmProjects/athena-script/.venv/lib/python3.9/site-packages/clp_ffi_py/ir/readers.py", line 74, in read_preamble
    self._metadata = Decoder.decode_preamble(self._decoder_buffer)
zstd.ZstdError: zstd decompress error: Unknown frame descriptor
```
# Initial Analysis
1. Through experiments, it was found that the latest version of `smart_open.open()` decompresses ZStandard files as it detects the file format from the file name's extension. `smart_open`'s manual: https://github.com/piskvorky/smart_open#compression-handling . With the default value of `compression="infer_from_extension"`, the file stream passed to `ClpIrStreamReader` is already decompressed. However, the `ClpIrStreamReader` still treats the input as a Zstandard compressed stream, which explains the decompressor error.
2. Setting `compression='disable'` in `smart_open.open()` resolved the issue.

### clp-ffi-py version

0.0.11

### Environment

macOS 14.5 (23F79); Python 3.9

### Reproduction steps

1. `pip install clp-ffi-py smart-open==7.0.4 requests`
2. Run sample code as described above.
3. Observe the exception as described above.

**Comment by junhaoliao** [comment]
@LinZhihao-723 
At the moment, the quickest and simplest fix might be to update the example code to include arg `compression='disable'` when calling `smart_open.open()`. I can prepare a PR to update the docs if that's agreed.

**Comment by LinZhihao-723** [comment]
> @LinZhihao-723 At the moment, the quickest and simplest fix might be to update the example code to include arg `compression='disable'` when calling `smart_open.open()`. I can prepare a PR to update the docs if that's agreed.

Sure, let's do it in the sample code and add an explanation why we are doing this.
Plans for future PR: We should properly setup a dependency to `smart_open`, meaning that our stream reader should have smart open as our backend. In that way, we should be able to discard this `compression` flag.
Feel free to add any comments @kirkrodrigues @jackluo923

**Comment by jackluo923** [comment]
I think setting `compression='disable'` and handling decompression outside is good. I see in the code that we have the following: 
```
   def __init__(
        self,
        istream: IO[bytes],
        decoder_buffer_size: int = DEFAULT_DECODER_BUFFER_SIZE,
        enable_compression: bool = True,
        allow_incomplete_stream: bool = False,
    ):
        self.__istream: Union[IO[bytes], ZstdDecompressionReader]
        if enable_compression:
            dctx: ZstdDecompressor = ZstdDecompressor()
            self.__istream = dctx.stream_reader(istream, read_across_frames=True)
```
where we have `read_across_frames=True` customized parameter. Potentially, we may want to play with buffer sizes as well in the future. So it may be better to just leave the decompression part outside of smart_open and only use smart_open to stream data from various platforms.

**Comment by kirkrodrigues** [comment]
> Sure, let's do it in the sample code and add an explanation why we are doing this. Plans for future PR: We should properly setup a dependency to `smart_open`, meaning that our stream reader should have smart open as our backend. In that way, we should be able to discard this `compression` flag. Feel free to add any comments @kirkrodrigues @jackluo923

* Sure, updating the example makes sense.
* What would using `smart_open` within the library look like? I.e., what would the `ClpIrStreamReader` interface look like?
